---
- name: Setup provider
  ansible.builtin.set_fact:
    provider:
    server: "{{ f5_ip }}"
    user: "{{ f5_user }}"
    password: "{{ f5_pass }}"
    validate_certs: "no"

- name: Set facts if creating appserver
  ansible.builtin.set_fact:
    pool_name: app_pool
    virtual_server_name: poolapp
    virtual_server_ip: 172.16.3.122
    virtual_server_fqdn: f5lb.shadowman.dev
  when: inventory_hostname is match("appserver.*")

- name: Create Nodes
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    host: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    monitors:
      - /Common/https_443
  delegate_to: localhost

- name: Create Pool
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    name: "{{ pool_name }}"
    lb_method: "round-robin"
    monitors: 
      - "/Common/https_443"
    monitor_type: "and_list"
  delegate_to: localhost

- name: Add Pool Members
  f5networks.f5_modules.bigip_pool_member:
    provider: "{{ provider }}"
    state: "present"
    host: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    port: "443"
    pool: "{{ pool_name }}"
  delegate_to: localhost

- name: Add Virtual Server
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    name: "{{ virtual_server_name }}"
    destination: "{{ virtual_server_ip }}"
    port: "443"
    enabled_vlans: "all"
    pool: "{{ pool_name }}"
    snat: "Automap"
  delegate_to: localhost
  notify: IDM_update

- name: Save Running Config
  f5networks.f5_modules.bigip_config:
    provider: "{{ provider }}"
    save: yes
  delegate_to: localhost

- name: Set stats for the e-mail body and ServiceNow
  ansible.builtin.set_stats:
    data:
      email_body: "{{ email_body }} Load Balancer: https://{{ virtual_server_fqdn }}"
      work_notes: "{{ work_notes }} [code]<a href='https://{{ virtual_server_fqdn }}'>Load Balancer</a>[/code]"
      expose_to_cloud_redhat_com_results: "{{ expose_to_cloud_redhat_com_results }} Load Balancer: https://{{ virtual_server_fqdn }}"
  run_once: true      
  when: email_body is defined