- name: IDM_update      
  community.general.ipa_host:
    name: "{{ virtual_server_fqdn }}"
    ip_address: "{{ virtual_server_ip }}"
    ipa_pass: "{{ IPA_PASS }}"
    ipa_host: "{{ IPA_HOST }}"
    ipa_user: "{{ IPA_USER }}"
    state: present
    force: yes
  delegate_to: localhost
  become: no