---
- name: Setup provider
  ansible.builtin.set_fact:
    provider:
      server: "{{ f5_ip }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      validate_certs: false

- name: Set facts if removing appserver
  ansible.builtin.set_fact:
    pool_name: app_pool
  when: inventory_hostname is match("appserver.*")

- name: Remove Pool Members
  f5networks.f5_modules.bigip_pool_member:
    provider: "{{ provider }}"
    state: absent
    host: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    port: "443"
    pool: "{{ pool_name }}"
  delegate_to: localhost

- name: Delete Nodes
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    host: "{{ ip_addr }}"
    name: "{{ inventory_hostname }}"
    state: absent
  delegate_to: localhost

- name: Save Running Config
  f5networks.f5_modules.bigip_config:
    provider: "{{ provider }}"
    save: true
  delegate_to: localhost
